modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="unbreakables"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
iconFile="unbreakables.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "unbreakables.mixins.json"
[[mixins]]
config = "unbreakables.neoforge.mixins.json"
[[dependencies.unbreakables]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.unbreakables]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.unbreakables]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.unbreakables]]
modId="shogi"
type="required"
versionRange="[${shogi_version},)"
ordering="NONE"
side="BOTH"
